In [2]:
import tensorflow as tf
from importlib import reload
import tf_preprocessing_layers
import numpy as np

/home/zdravko/Machine_Learning_Intern/venv/lib/python3.13/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [71]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import Discretization

age = tf.constant([[10.], [93.], [57.], [18.], [37.], [5.]])
discretize_layer = Discretization(bin_boundaries=[18., 50.])
age_categories = discretize_layer(age)
age_categories

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.]], dtype=float32)>

In [92]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import Discretization

x = tf.constant([[5.0, 50.0],
                 [15.0, 150.0],
                 [25.0, 250.0]])

bins_list = [[0.0, 10.0, 20.0], [0.0, 100.0, 200.0]]
layer = Discretization(bin_boundaries=bins_list)

y = layer(x)
y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [2., 2.],
       [3., 3.]], dtype=float32)>

In [91]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import Discretization

discretize_layer = Discretization(num_bins=3)
discretize_layer.adapt(age)
age_categories = discretize_layer(age)
age_categories 

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.]], dtype=float32)>

In [32]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import CategoryEncoding

onehot_layer = CategoryEncoding(num_tokens=3)
onehot_layer(age_categories)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)>

In [33]:
two_age_categories = np.array([[1, 0], [2, 2], [2, 0]])
onehot_layer(two_age_categories)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.]], dtype=float32)>

In [34]:
onehot_layer = CategoryEncoding(num_tokens=3 + 3)
onehot_layer(two_age_categories + [0, 3])

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0.]], dtype=float32)>

In [2]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import StringLookup

cities = ["Auckland", "Paris", "Paris", "San Francisco"]
str_lookup_layer = StringLookup()
str_lookup_layer.adapt(cities)
str_lookup_layer(tf.constant([["Paris"], ["Auckland"], ["Auckland"], ["Montreal"]]))

2026-02-06 11:35:41.957554: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


<tf.Tensor: shape=(4, 1), dtype=int64, numpy=
array([[1],
       [2],
       [2],
       [0]])>

In [86]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import StringLookup

str_lookup_layer = StringLookup(output_mode="one_hot")
str_lookup_layer.adapt(cities)
str_lookup_layer(tf.constant([["Paris"], ["Auckland"], ["Auckland"], ["Montreal"]]))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]], dtype=float32)>

In [90]:
str_lookup_layer = StringLookup(num_oov_indices=5)
str_lookup_layer.adapt(cities)
str_lookup_layer(tf.constant([["Paris"], ["Auckland"], ["Foo"], ["Bar"], ["Baz"]]))

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[5],
       [6],
       [4],
       [3],
       [4]])>

In [89]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import Hashing

hashing_layer = Hashing(num_bins=10)
hashing_layer(tf.constant([["Paris"], ["Tokyo"], ["Auckland"], ["Montreal"]]))

<tf.Tensor: shape=(4, 1), dtype=int64, numpy=
array([[0],
       [1],
       [9],
       [1]])>

In [57]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import Embedding

tf.random.set_seed(42)
embedding_layer = Embedding(input_dim=5, output_dim=2)
embedding_layer(np.array([2, 4, 2]))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.0105833 ,  0.02062872],
       [-0.04998725, -0.02009691],
       [-0.0105833 ,  0.02062872]], dtype=float32)>

In [ ]:
tf.random.set_seed(42)
ocean_prox = ["<1H OCEAN", "INLAND", "NEAR OCEAN", "NEAR BAY", "ISLAND"]

str_lookup_layer = tf.keras.layers.StringLookup()
str_lookup_layer.adapt(ocean_prox)

lookup_and_embed = tf.keras.Sequential([
    str_lookup_layer,
    tf.keras.layers.Embedding(input_dim=str_lookup_layer.vocabulary_size(), output_dim=2)
])

lookup_and_embed(np.array([["<1H OCEAN"], ["ISLAND"], ["<1H OCEAN"]]))

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[-0.00186092,  0.03262634]],

       [[-0.04097522, -0.02453467]],

       [[-0.00186092,  0.03262634]]], dtype=float32)>

In [ ]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import Embedding, StringLookup

tf.random.set_seed(42)
ocean_prox = ["<1H OCEAN", "INLAND", "NEAR OCEAN", "NEAR BAY", "ISLAND"]

str_lookup_layer = StringLookup()
str_lookup_layer.adapt(ocean_prox)

lookup_and_embed = tf.keras.Sequential([
    tf.keras.Input(shape=(1,), dtype=tf.string),
    str_lookup_layer,
    Embedding(input_dim=str_lookup_layer.vocabulary_size(), output_dim=2)
])

lookup_and_embed(tf.constant([["<1H OCEAN"], ["ISLAND"], ["<1H OCEAN"]]))

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[ 0.02691821, -0.03863335]],

       [[-0.03370287, -0.02215749]],

       [[ 0.02691821, -0.03863335]]], dtype=float32)>

## hw 123

In [26]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import TextVectorization

train_data = ["To be", "!(to be)", "That's the question", "Be, be, be."]
text_vec_layer = TextVectorization()
text_vec_layer.adapt(train_data)
text_vec_layer(tf.constant(["Be good!", "Question: be or be?"]))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 1, 0, 0],
       [6, 2, 1, 2]], dtype=int32)>

In [49]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import TextVectorization

text_vec_layer = TextVectorization(output_mode="tf_idf")
text_vec_layer.adapt(train_data)
text_vec_layer(tf.constant(["Be good!", "Question: be or be?"]))

# <tf.Tensor: shape=(2, 6), dtype=float32, numpy=
# [0.96725637, 0.6931472 , 0. , 0. , 0. , 0.],
# [0.96725637, 1.3862944 , 0. , 0. , 0. , 1.0986123 ]], dtype=float32)>

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0.96725637, 0.6931472 , 0.        , 0.        , 0.        ,
        0.        ],
       [0.96725637, 1.3862944 , 0.        , 0.        , 0.        ,
        1.0986123 ]], dtype=float32)>

In [73]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import TextVectorization

text_vec_layer = TextVectorization(output_mode="one_hot")
text_vec_layer.adapt(train_data)
text_vec_layer(tf.constant(["Be good!", "Question: be or be?"]))


# [[[0, 1, 0, 0, 0, 0],
#   [1, 0, 0, 0, 0, 0]], 
  
# [[0, 0, 0, 0, 0, 1],
#  [0, 1, 0, 0, 0, 0],
#  [1, 0, 0, 0, 0, 0],
#  [0, 1, 0, 0, 0, 0]]]>

<tf.Tensor: shape=(2, 4, 6), dtype=float32, numpy=
array([[[0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.]]], dtype=float32)>

In [74]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import TextVectorization

text_vec_layer = TextVectorization(output_mode="multi_hot")
text_vec_layer.adapt(train_data)
text_vec_layer(tf.constant(["Be good!", "Question: be or be?"]))

# [[1, 1, 0, 0, 0, 0],
# [1, 1, 0, 0, 0, 1]]

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 1.]], dtype=float32)>

In [81]:
reload(tf_preprocessing_layers)
from tf_preprocessing_layers import TextVectorization

text_vec_layer = TextVectorization(output_mode="count")
text_vec_layer.adapt(train_data)
text_vec_layer(tf.constant(["Be good!", "Question: be or be?"]))

# [[1, 1, 0, 0, 0, 0],
# [1, 2, 0, 0, 0, 1]]

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 1., 0., 0., 0., 0.],
       [1., 2., 0., 0., 0., 1.]], dtype=float32)>