In [1]:
import tensorflow as tf
from importlib import reload
import tf_data
import numpy as np

2026-02-06 11:32:52.012328: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-06 11:32:52.980575: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-06 11:32:58.749636: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
/home/zdravko/Machine_Learning_Intern/venv/lib/python3.13/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [15]:
reload(tf_data)
from tf_data import Dataset

X = tf.range(10)
dataset = Dataset.from_tensor_slices(X)
dataset

In [16]:
a = 5

for item, i in zip(dataset, range(a)):
    print(item)

for item in dataset:
    print(item)


tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [4]:
reload(tf_data)
from tf_data import Dataset

X_nested = {"a": [1, 2, 3], 'c': [4, 5, 6], "b": [7, 8, 9]}
dataset = Dataset.from_tensor_slices(X_nested)

for item in dataset:
    print(item)

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=5>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=3>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=6>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>}


In [ ]:
X_nested = {"a": [1, 2, 3], "b": [7, 8, 9]}

# dataset = tf.data.Dataset.from_tensor_slices(tf.range(10))
dataset = tf.data.Dataset.from_tensor_slices(X_nested)
dataset = dataset.repeat(3).batch(3).take(2)

for item in dataset:
    print(item)

{'a': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>, 'b': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9], dtype=int32)>}
{'a': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>, 'b': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9], dtype=int32)>}


In [8]:
reload(tf_data)
from tf_data import Dataset

dataset = Dataset.from_tensor_slices(tf.range(10))
dataset = dataset.repeat(3).batch(7)

for item in dataset:
    print(item)

print('\n')

dataset = dataset.map(lambda x: x * 2) 
for item in dataset:
    print(item)

print('\n')

dataset = dataset.filter(lambda x: tf.reduce_sum(x) > 50)
for item in dataset:
    print(item)

print('\n')

for item in dataset.take(2):
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)


tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)


In [18]:
reload(tf_data)
from tf_data import Dataset

dataset = Dataset.from_tensor_slices(tf.range(10)).repeat(2)
dataset = dataset.shuffle(buffer_size=4, seed=42).batch(7)

for item in dataset:
    print(item)

tf.Tensor([3 2 0 5 4 6 1], shape=(7,), dtype=int32)
tf.Tensor([0 8 2 3 1 5 7], shape=(7,), dtype=int32)
tf.Tensor([6 8 9 4 9 7], shape=(6,), dtype=int32)


In [20]:
train_filepaths = ['datasets/housing_01.csv', 
                   'datasets/housing_02.csv',
                   'datasets/housing_03.csv',
                   'datasets/housing_04.csv']

In [ ]:
reload(tf_data)
from tf_data import Dataset, TextLineDataset

filepath_dataset = Dataset.list_files(train_filepaths, shuffle=True)

for item in filepath_dataset:
    print(item)

n_readers = 4
dataset = filepath_dataset.interleave(
                            lambda filepath: TextLineDataset(filepath).skip(1),
                            cycle_length=n_readers)

print('\n')

for line in dataset.take(4):
    print(line)

tf.Tensor([b'datasets/housing_03.csv'], shape=(1,), dtype=string)
tf.Tensor([b'datasets/housing_01.csv'], shape=(1,), dtype=string)
tf.Tensor([b'datasets/housing_04.csv'], shape=(1,), dtype=string)
tf.Tensor([b'datasets/housing_02.csv'], shape=(1,), dtype=string)


-120.84,37.49,25.0,2383.0,576.0,1234.0,583.0,1.4529,86100.0,INLAND

-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY

-117.32,33.12,25.0,2670.0,527.0,936.0,461.0,2.7717,354000.0,NEAR OCEAN

-122.21,37.8,50.0,2833.0,605.0,1260.0,552.0,2.8929,216700.0,NEAR BAY



In [30]:
reload(tf_data)
from tf_data import Dataset

a = Dataset.range(1, 4)  
b = Dataset.range(4, 8) 
ds = a.concatenate(b)

for item in ds:
    print(item)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [33]:
reload(tf_data)
from tf_data import Dataset

dataset = Dataset.range(7).window(3)
for window in dataset:
  print(window)

print('\n')

for window in dataset:
  print(list(window))



[<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>]
[<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=4>, <tf.Tensor: shape=(), dtype=int32, numpy=5>]
[<tf.Tensor: shape=(), dtype=int32, numpy=6>]


In [132]:
reload(tf_data)
from tf_data import Dataset

Dataset.range(5).reduce(np.int64(0), lambda x, _: x + 1)

np.int64(5)

In [134]:
Dataset.range(5).reduce(np.int64(0), lambda x, y: x + y)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [49]:
reload(tf_data)
from tf_data import Dataset

A = Dataset.range(10)
B = A.shard(num_shards=3, index=0)
list(B)

[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>]

In [50]:
C = A.shard(num_shards=3, index=1)
list(C)

[<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>]

In [51]:
D = A.shard(num_shards=3, index=2)
list(D)

[<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>]

In [52]:
reload(tf_data)
from tf_data import Dataset

dataset = Dataset.range(100)

def dataset_fn(ds):
  return ds.filter(lambda x: x < 5)

dataset = dataset.apply(dataset_fn)
list(dataset)

[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>]

In [80]:
reload(tf_data)
from tf_data import Dataset

A = (Dataset
     .range(1, 5)
     .map(lambda x: tf.fill([x], x)))

for item in A:
    print(item)

print('\n')

B = A.padded_batch(2)
# B = A.batch(2)
for element in B:
  print(element, '\n')

tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 4 4 4], shape=(4,), dtype=int32)


tf.Tensor(
[[1 0]
 [2 2]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3 3 0]
 [4 4 4 4]], shape=(2, 4), dtype=int32) 



In [146]:
def gen():
  ragged_tensor = tf.ragged.constant([[1, 2], [3]])
  yield 42, ragged_tensor

dataset = tf.data.Dataset.from_generator(
     gen,
     output_signature=(
         tf.TensorSpec(shape=(), dtype=tf.int32),
         tf.RaggedTensorSpec(shape=(2, None), dtype=tf.int32)))

list(dataset.take(1))

[(<tf.Tensor: shape=(), dtype=int32, numpy=42>,
  <tf.RaggedTensor [[1, 2], [3]]>)]

In [144]:
reload(tf_data)
from tf_data import Dataset

def gen():
  ragged_tensor = tf.ragged.constant([[1, 2], [3]])
  yield 42, ragged_tensor

dataset = Dataset.from_generator(
     gen,
     output_signature=(
         tf.TensorSpec(shape=(), dtype=tf.int32),
         tf.RaggedTensorSpec(shape=(2, None), dtype=tf.int32)))

list(dataset.take(1))

[[<tf.Tensor: shape=(), dtype=int32, numpy=42>,
  <tf.RaggedTensor [[1, 2], [3]]>]]

In [84]:
record_defaults = [0., 0., 0., 0., 0., 0., 0., 0., 0., ""]

In [87]:
ds = tf.data.experimental.CsvDataset('datasets/housing_01.csv',
                                     record_defaults=record_defaults,
                                     header=True)

rows = 10
for item, _ in zip(ds, range(rows)):
    print(item)

(<tf.Tensor: shape=(), dtype=float32, numpy=-122.2300033569336>, <tf.Tensor: shape=(), dtype=float32, numpy=37.880001068115234>, <tf.Tensor: shape=(), dtype=float32, numpy=41.0>, <tf.Tensor: shape=(), dtype=float32, numpy=880.0>, <tf.Tensor: shape=(), dtype=float32, numpy=129.0>, <tf.Tensor: shape=(), dtype=float32, numpy=322.0>, <tf.Tensor: shape=(), dtype=float32, numpy=126.0>, <tf.Tensor: shape=(), dtype=float32, numpy=8.325200080871582>, <tf.Tensor: shape=(), dtype=float32, numpy=452600.0>, <tf.Tensor: shape=(), dtype=string, numpy=b'NEAR BAY'>)
(<tf.Tensor: shape=(), dtype=float32, numpy=-122.22000122070312>, <tf.Tensor: shape=(), dtype=float32, numpy=37.86000061035156>, <tf.Tensor: shape=(), dtype=float32, numpy=21.0>, <tf.Tensor: shape=(), dtype=float32, numpy=7099.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1106.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2401.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1138.0>, <tf.Tensor: shape=(), dtype=float32, numpy=8.301400184631

In [91]:
row = '-117.32,33.12,25.0,2670.0,527.0,936.0,461.0,2.7717,354000.0,NEAR OCEAN'

for a in tf.strings.split(row, sep=','):
    print(a)

tf.strings.split(row, sep=',')

tf.Tensor(b'-117.32', shape=(), dtype=string)
tf.Tensor(b'33.12', shape=(), dtype=string)
tf.Tensor(b'25.0', shape=(), dtype=string)
tf.Tensor(b'2670.0', shape=(), dtype=string)
tf.Tensor(b'527.0', shape=(), dtype=string)
tf.Tensor(b'936.0', shape=(), dtype=string)
tf.Tensor(b'461.0', shape=(), dtype=string)
tf.Tensor(b'2.7717', shape=(), dtype=string)
tf.Tensor(b'354000.0', shape=(), dtype=string)
tf.Tensor(b'NEAR OCEAN', shape=(), dtype=string)


<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'-117.32', b'33.12', b'25.0', b'2670.0', b'527.0', b'936.0',
       b'461.0', b'2.7717', b'354000.0', b'NEAR OCEAN'], dtype=object)>

In [100]:
reload(tf_data)
from tf_data import CsvDataset

ds = CsvDataset('datasets/housing_01.csv',
                record_defaults=record_defaults,
                header=True)

rows = 10
for item, _ in zip(ds, range(rows)):
    print(item)

(<tf.Tensor: shape=(), dtype=float32, numpy=-122.2300033569336>, <tf.Tensor: shape=(), dtype=float32, numpy=37.880001068115234>, <tf.Tensor: shape=(), dtype=float32, numpy=41.0>, <tf.Tensor: shape=(), dtype=float32, numpy=880.0>, <tf.Tensor: shape=(), dtype=float32, numpy=129.0>, <tf.Tensor: shape=(), dtype=float32, numpy=322.0>, <tf.Tensor: shape=(), dtype=float32, numpy=126.0>, <tf.Tensor: shape=(), dtype=float32, numpy=8.325200080871582>, <tf.Tensor: shape=(), dtype=float32, numpy=452600.0>, <tf.Tensor: shape=(), dtype=string, numpy=b'NEAR BAY\n'>)
(<tf.Tensor: shape=(), dtype=float32, numpy=-122.22000122070312>, <tf.Tensor: shape=(), dtype=float32, numpy=37.86000061035156>, <tf.Tensor: shape=(), dtype=float32, numpy=21.0>, <tf.Tensor: shape=(), dtype=float32, numpy=7099.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1106.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2401.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1138.0>, <tf.Tensor: shape=(), dtype=float32, numpy=8.3014001846

In [102]:
ds = tf.data.experimental.make_csv_dataset('datasets/housing_01.csv', 2)

i = 5
for item, _ in zip(ds, range(i)):
    print(item)

OrderedDict({'longitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-121.97, -121.63], dtype=float32)>, 'latitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([39.79, 38.04], dtype=float32)>, 'housing_median_age': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([16., 25.], dtype=float32)>, 'total_rooms': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1453., 2019.], dtype=float32)>, 'total_bedrooms': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([299., 411.], dtype=float32)>, 'population': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([904., 888.], dtype=float32)>, 'households': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([286., 326.], dtype=float32)>, 'median_income': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.5735, 3.2619], dtype=float32)>, 'median_house_value': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 89600., 183800.], dtype=float32)>, 'ocean_proximity': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'INLAND', b'I

In [ ]:
reload(tf_data)
from tf_data import make_csv_dataset

ds = make_csv_dataset('datasets/housing_01.csv', 2, shuffle=False)

i = 5
for item, _ in zip(ds, range(i)):
    print(item)

{'longitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-122.23, -122.22], dtype=float32)>, 'latitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([37.88, 37.86], dtype=float32)>, 'housing_median_age': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([41., 21.], dtype=float32)>, 'total_rooms': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 880., 7099.], dtype=float32)>, 'total_bedrooms': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 129., 1106.], dtype=float32)>, 'population': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 322., 2401.], dtype=float32)>, 'households': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 126., 1138.], dtype=float32)>, 'median_income': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.3252, 8.3014], dtype=float32)>, 'median_house_value': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([452600., 358500.], dtype=float32)>, 'ocean_proximity\n': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'NEAR BAY\n', b'N

In [107]:
reload(tf_data)
from tf_data import make_csv_dataset

ds = make_csv_dataset('datasets/housing_01.csv', 2, shuffle=True, shuffle_buffer_size=10)

i = 5
for item, _ in zip(ds, range(i)):
    print(item)

{'longitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-122.22, -122.24], dtype=float32)>, 'latitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([37.86, 37.85], dtype=float32)>, 'housing_median_age': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([21., 52.], dtype=float32)>, 'total_rooms': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([7099., 1467.], dtype=float32)>, 'total_bedrooms': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1106.,  190.], dtype=float32)>, 'population': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2401.,  496.], dtype=float32)>, 'households': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1138.,  177.], dtype=float32)>, 'median_income': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.3014, 7.2574], dtype=float32)>, 'median_house_value': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([358500., 352100.], dtype=float32)>, 'ocean_proximity\n': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'NEAR BAY\n', b'N

In [108]:
reload(tf_data)
from tf_data import make_csv_dataset

ds = make_csv_dataset('datasets/housing_01.csv', 2, shuffle=True, shuffle_buffer_size=10, label_name='total_rooms')

i = 5
for item, _ in zip(ds, range(i)):
    print(item)

({'longitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-122.25, -122.26], dtype=float32)>, 'latitude': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([37.84, 37.85], dtype=float32)>, 'housing_median_age': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([52., 52.], dtype=float32)>, 'total_bedrooms': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([707., 434.], dtype=float32)>, 'population': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1551.,  910.], dtype=float32)>, 'households': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([714., 402.], dtype=float32)>, 'median_income': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.6912, 3.2031], dtype=float32)>, 'median_house_value': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([261100., 281500.], dtype=float32)>, 'ocean_proximity\n': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'NEAR BAY\n', b'NEAR BAY\n'], dtype=object)>}, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([3549., 2202.], dtype

In [6]:
reload(tf_data)
from tf_data import Dataset

dataset = Dataset.range(3)
dataset = dataset.prefetch(2)
list(dataset)

[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>]

In [2]:
reload(tf_data)
from tf_data import Dataset


dataset = Dataset.range(5)
dataset = dataset.map(lambda x: x**2)
dataset = dataset.cache()
(list(dataset))

2026-02-06 11:33:08.054302: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=16>]

In [3]:
list(dataset)

read from buffer


[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=16>]

In [176]:
reload(tf_data)
from tf_data import Dataset

dataset = Dataset.range(5)
dataset = dataset.cache("test_cache.pkl")
list(dataset)

[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>]

In [177]:
dataset = Dataset.range(10)
dataset = dataset.cache("test_cache.pkl")  
list(dataset)

read from File


[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>]

## Task 3

към data pipeline-a от книгата да се добави обработка на липсващи данни

In [122]:
import pandas as pd

housing = pd.read_csv('datasets/housing_01.csv')
X_mean = housing.mean(axis=0, numeric_only=True).values
X_median = housing.median(axis=0, numeric_only=True).values
X_std = housing.std(axis=0, numeric_only=True).values

In [123]:
n_num_inputs = 9

def parse_csv_line(line, record_defaults=None, strategy="zero"):
    if record_defaults is not None:
        defs = record_defaults
    else:
        match strategy:
            case 'zero':
                defs = [0.] * n_num_inputs + [tf.constant([], dtype=tf.string)]

            case 'mean':
                defs = X_mean.tolist() + [tf.constant([], dtype=tf.string)]

            case 'median':
                defs = X_median.tolist() + [tf.constant([], dtype=tf.string)]

    fields = tf.io.decode_csv(line, record_defaults=defs)
    return tf.stack(fields[:-1]), tf.stack(fields[-1:])

def preprocess(line, record_defaults=None, strategy="zero"):
    x, y = parse_csv_line(line, record_defaults, strategy)
    return (x - X_mean) / X_std, y


def csv_reader_dataset(filepaths, n_readers=5, n_read_threads=None,
                        n_parse_threads=5, shuffle_buffer_size=10_000, seed=42,
                        batch_size=32, record_defaults=None, strategy="zero"):
    
    dataset = tf.data.Dataset.list_files(filepaths, seed=seed)
    dataset = dataset.interleave(
        lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
        cycle_length=n_readers, num_parallel_calls=n_read_threads)
    
    dataset = dataset.map(lambda line: preprocess(line, record_defaults, strategy), 
                          num_parallel_calls=n_parse_threads)
    
    dataset = dataset.shuffle(shuffle_buffer_size, seed=seed)
    return dataset.batch(batch_size).prefetch(1)

In [124]:
ds = csv_reader_dataset('datasets/housing_*.csv', batch_size=3)

i = 5
for item, _ in zip(ds, range(i)):
    print(item)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: name node, strategy, outside of any statement?
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: name node, strategy, outside of any statement?
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(<tf.Tensor: shape=(3, 9), dtype=float32, numpy=
array([[ 0.72782165, -0.7729913 ,  1.1457095 , -0.86517936, -0.7934171 ,
        -0.5478341 , -0.73020923, -0.3767935 , -0.45069516],
       [-0.39870223,  1.1003497 , -0.7502449 , -0.28765202, -0.24643157,
        -0.47018114, -0.28261188, -0.62740976, -0.7371906 ],
       [ 1.2687488 , -1.4100207 , -0.51325065,  0.34819245,  0.2303

## Task 2

да се имплеметира класа Normalization така че да работят примерите в книгата

In [ ]:
class Normalization(tf.keras.layers.Layer):
    def adapt(self, X):
        self.mean_ = tf.reduce_mean(X, axis=0, keepdims=True)
        self.std_  = tf.math.reduce_std(X, axis=0, keepdims=True)

    def call(self, inputs):
        eps = tf.keras.backend.epsilon()
        return (inputs - self.mean_) / (self.std_ + eps)

In [126]:
np.random.seed(13)
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

X, y = fetch_california_housing(return_X_y=True)
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, random_state=42, test_size=0.2, shuffle=True) 
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, random_state=42, test_size=0.1, shuffle=True) 

In [127]:
norm_layer = tf.keras.layers.Normalization()

model = tf.keras.models.Sequential([
    norm_layer,
    tf.keras.layers.Dense(1)
])

model.compile(loss="mse", optimizer=tf.keras.optimizers.SGD(learning_rate=2e-3))
norm_layer.adapt(X_train) 
model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=5)

Epoch 1/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.0356 - val_loss: 0.7902
Epoch 2/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6353 - val_loss: 0.6305
Epoch 3/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.5763 - val_loss: 0.6078
Epoch 4/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5588 - val_loss: 0.5943
Epoch 5/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5469 - val_loss: 0.5832


In [128]:
norm_layer = tf.keras.layers.Normalization()
norm_layer.adapt(X_train)
X_train_scaled = norm_layer(X_train)
X_valid_scaled = norm_layer(X_valid)

model = tf.keras.models.Sequential([tf.keras.layers.Dense(1)])
model.compile(loss="mse", optimizer=tf.keras.optimizers.SGD(learning_rate=2e-3))
model.fit(X_train_scaled, y_train, epochs=5, validation_data=(X_valid_scaled, y_valid))

Epoch 1/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 2.2045 - val_loss: 0.9414
Epoch 2/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.7968 - val_loss: 0.7595
Epoch 3/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.7112 - val_loss: 0.7059
Epoch 4/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6662 - val_loss: 0.6785
Epoch 5/5
465/465 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6335 - val_loss: 0.6442


In [130]:
final_model = tf.keras.Sequential([norm_layer, model])
X_new = X_test[:3]
y_pred = final_model(X_new)
y_pred

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[1.0239493],
       [1.5350587],
       [2.5114791]], dtype=float32)>