# numpy Test


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

2.3.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.7/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.7/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.7/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.7/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.30
Compilers:
  c:
    commands: cc
    linker: ld.bfd


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_arr = np.zeros(10)
null_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
null_arr.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [127]:
help(np.add)
np.add?

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            ~/Machine_Learning_Intern/venv/lib/python3.13/site-packages/numpy/__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is T

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_arr[4] = 1
null_arr 

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
range_vec = np.arange(10, 50)
range_vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
range_vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
t10 = np.array([1,2,0,0,4,0])
np.where(t10 != 0)[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.randn(3, 3, 3)

array([[[-0.43215867, -1.48923013, -0.09665435],
        [-1.00916977, -1.93991097, -0.36661764],
        [ 1.42555261, -1.31926475, -0.76738539]],

       [[-0.61294411, -0.38044076, -1.50086293],
        [ 1.19616915,  1.62829037, -1.25197032],
        [ 1.96040385,  0.6346987 ,  1.13319154]],

       [[-0.27160412, -0.64516653, -0.05290528],
        [-0.57832132,  0.34646294,  0.43876666],
        [-0.52185364,  0.74646645,  0.77636153]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
mat13 = np.random.randint(10, 100, size=(10, 10))
print(mat13)

print('max:', mat13.max(), 'min:', mat13.min())

[[99 91 50 26 51 97 82 56 28 68]
 [19 42 27 80 86 33 67 22 29 68]
 [75 28 88 97 11 71 77 39 47 12]
 [47 59 69 45 56 72 95 58 38 39]
 [21 69 94 92 25 74 19 55 75 93]
 [38 20 26 70 62 91 93 79 78 61]
 [71 22 77 81 63 36 34 67 26 59]
 [98 14 52 72 69 49 44 86 71 14]
 [46 37 23 63 66 19 79 24 28 48]
 [32 22 12 27 52 87 51 19 60 36]]
max: 99 min: 11


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr14 = np.random.standard_normal(30)
print(arr14)

arr14.mean()

[-0.35341863  1.43956879 -1.04461205 -0.26767421 -0.14582645  1.90919914
  1.61572967 -1.9831587   1.07667397  0.76760693  0.3178733   1.151256
  0.07695255  0.17466384 -0.17010256  2.0871356   0.57447911  0.14910009
  0.32740931 -0.6579258  -0.14326229  2.58842403  1.22815078  0.90190235
  0.80538215 -0.26919088  1.19600557  2.22992164  0.28984401 -2.07077751]


np.float64(0.46004432484315505)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
mat15 = np.zeros((10, 10), dtype=np.int8)
mat15[[0, -1]] = 1
mat15[:, [0, -1]] = 1

mat15

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
np.pad(mat15, 1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan -> nan
np.nan == np.nan -> False
np.inf > np.nan -> False
np.nan - np.nan -> nan
np.nan in set([np.nan]) -> True
0.3 == 3 * 0.1 -> False
```

In [18]:
3 * 0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
mat19 = np.zeros((8, 8))
mat19[::2, ::2] = 1
mat19[1::2, 1::2] = 1

mat19

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
[1, 5, 3]

[1, 5, 3]

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
np.tile([[1, 0], [0, 1]], (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
mat22 = np.random.rand(5, 5)
(mat22 - mat22.mean(
    
)) / mat22.std()

array([[-1.42822181, -0.5395204 , -0.2558161 , -0.31872909,  0.22143761],
       [ 0.91167581, -1.3079672 , -0.3999964 , -1.2462675 ,  0.16090482],
       [-1.22556972,  0.08011882, -0.38540833,  1.6994603 ,  0.09018835],
       [ 1.59434542, -1.09568095, -0.66248843, -0.06026369,  1.06548897],
       [-1.45504958,  0.67955954,  0.60839562,  1.68417522,  1.58522872]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
rgba = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
pixel = np.array((255, 128, 64, 255), dtype=rgba)
pixel

array((255, 128, 64, 255),
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
np.random.randint(1, 100, size=(5, 3)) @ np.random.randint(1, 10, size=(3, 2))

array([[ 522,  500],
       [ 416,  400],
       [ 876,  696],
       [1050,  916],
       [ 466,  372]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
mat25 = np.random.randint(0, 20, size=10)
mat25[(mat25 > 3) & (mat25 < 8)] *= -1
mat25

array([16, 16, 10, 12,  0, 12, -4, 12,  8,  8])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1)) -> 9 
from numpy import *
print(sum(range(5),-1)) -> 10
```

In [27]:
from numpy import *
print(sum(range(5)))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z ->
2 << Z >> 2 ->
Z <- Z
1j*Z ->
Z/1/1 ->
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0) -> zerodeverror / nan
np.array(0) // np.array(0) -> zerodeverror / nan
np.array([np.nan]).astype(int).astype(float) -> float to int RuntimeWarning / array([-9.22337204e+18])
```

In [28]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_4454/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
arr29 = np.random.standard_normal(10)
print(arr29)

np.copysign(np.ceil(np.abs(arr29)), arr29)

[ 0.3062322   0.25662033 -0.27048483  1.49776092  0.04936714  0.55898394
 -0.31261904 -0.65522286 -0.92753272 -1.21029903]


array([ 1.,  1., -1.,  2.,  1.,  1., -1., -1., -1., -2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
arr1, arr2 = np.array([1, 2, 3]), np.array([5, 2, 6])
arr1 == arr2

array([False,  True, False])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
np.seterr(all='ignore')

np.array(0) / np.array(0)

np.float64(nan)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
day = np.timedelta64(1, 'D')
print(day)
today = np.datetime64('today')
print('yesterday:', today - day)
print('today:', today)
print('tomorrow', today + day)

1 days
yesterday: 2025-12-20
today: 2025-12-21
tomorrow 2025-12-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
np.arange('2016-07-01', '2016-08-01', dtype=np.datetime64)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

``` python
t = -A/2
A += B
A *= t
```

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [35]:
arr = np.random.normal(loc=100, scale=50, size=10)
print(arr)

print(arr.astype(int))
print(arr.round(0))
print(np.ceil(arr) - 1)
print(np.floor(arr))

[ 20.58082543  68.52758515  57.23299492  66.01614059  66.40321667
 142.98238601  68.63008684 156.21585212 138.886452   130.20469751]
[ 20  68  57  66  66 142  68 156 138 130]
[ 21.  69.  57.  66.  66. 143.  69. 156. 139. 130.]
[ 20.  68.  57.  66.  66. 142.  68. 156. 138. 130.]
[ 20.  68.  57.  66.  66. 142.  68. 156. 138. 130.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
def gen():
    for i in range(10):
        yield i

np.fromiter(gen(), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
np.random.rand(10)

array([0.88710939, 0.25958165, 0.16248732, 0.72811272, 0.48880153,
       0.70697063, 0.71000871, 0.98701567, 0.82912981, 0.98183663])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [39]:
np.sort(np.random.randint(0, 100, 10))

array([ 3, 25, 28, 61, 62, 71, 73, 86, 95, 99])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [40]:
arr41 = np.arange(5)
np.add.reduce(arr41)

np.int64(10)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [41]:
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)
print(A == B)
np.array_equal(A, B)

[False  True False False False False False False False False]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [42]:
arr43 = np.array((1, 2, 3))
arr43.flags.writeable = False
# arr43[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [43]:
X = np.random.randn(10, 2)
x = X[:, 0]
y = X[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar = np.c_[r, theta]

print(X)
polar

[[ 1.38644537  0.09810433]
 [-1.72661358 -0.02688461]
 [ 0.32126819 -1.66347879]
 [-0.33588088  0.68961309]
 [ 0.25087241 -0.79159525]
 [-0.80054878  1.27501078]
 [-0.42986916 -1.11359342]
 [ 0.53758957  1.59130172]
 [ 0.85437951 -1.25270134]
 [ 0.73418844 -0.12827118]]


array([[ 1.38991195,  0.07064187],
       [ 1.72682287, -3.1260232 ],
       [ 1.69421809, -1.38001487],
       [ 0.76706074,  2.02403602],
       [ 0.8303975 , -1.26388973],
       [ 1.5055002 ,  2.13146117],
       [ 1.19368246, -1.93919306],
       [ 1.67965583,  1.24500419],
       [ 1.51631955, -0.97223306],
       [ 0.74530944, -0.17296575]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [44]:
arr45 = np.random.randn(10)
print(arr45)

arr45[arr45.argmax()] = 0
arr45

[ 0.25091383 -0.48201981 -0.42273543  0.8588727  -0.44280745  0.37023825
  0.77415956 -0.05756067  0.4203369   0.30861635]


array([ 0.25091383, -0.48201981, -0.42273543,  0.        , -0.44280745,
        0.37023825,  0.77415956, -0.05756067,  0.4203369 ,  0.30861635])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [45]:
dtp = np.dtype([('x', np.float64), ('y', np.float64)])

x = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, x)

structured = np.zeros(X.shape, dtype=dtp)
structured['x'] = X
structured['y'] = Y

structured

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [46]:
X = np.array([1, 2, 3])
Y = np.array([4, 5])

prod = np.transpose([np.tile(X, len(Y)), np.repeat(Y, len(X))])
vals = 1 / (prod[:, 0] - prod[:, 1])
vals.reshape(len(X), len(Y))

array([[-0.33333333, -0.5       ],
       [-1.        , -0.25      ],
       [-0.33333333, -0.5       ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [47]:
for name, tp in np.sctypeDict.items():
    try:
        info = np.iinfo(tp)
    except:
        continue

    print(f'{name} max: {info.max}, min: {info.min}')

int8 max: 127, min: -128
byte max: 127, min: -128
uint8 max: 255, min: 0
ubyte max: 255, min: 0
int16 max: 32767, min: -32768
short max: 32767, min: -32768
uint16 max: 65535, min: 0
ushort max: 65535, min: 0
int32 max: 2147483647, min: -2147483648
intc max: 2147483647, min: -2147483648
uint32 max: 4294967295, min: 0
uintc max: 4294967295, min: 0
int64 max: 9223372036854775807, min: -9223372036854775808
long max: 9223372036854775807, min: -9223372036854775808
uint64 max: 18446744073709551615, min: 0
ulong max: 18446744073709551615, min: 0
longlong max: 9223372036854775807, min: -9223372036854775808
ulonglong max: 18446744073709551615, min: 0
intp max: 9223372036854775807, min: -9223372036854775808
uintp max: 18446744073709551615, min: 0
int_ max: 9223372036854775807, min: -9223372036854775808
uint max: 18446744073709551615, min: 0
int max: 9223372036854775807, min: -9223372036854775808


#### 49. How to print all the values of an array? (★★☆)

In [48]:
arr49 = np.arange(500)
np.set_printoptions(threshold=np.inf)  
print(arr49)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [49]:
arr50 = np.arange(5, 20, 3)
print(arr50)
sc = 10
arr50[np.abs(arr50 - sc).argmin()]

[ 5  8 11 14 17]


np.int64(11)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [50]:
dtp = np.dtype([('x', np.float64), ('y', np.float64), ('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])

arr51 = np.array([(0, 0, 50, 50, 50), (5, 5, 100, 100, 100)], dtype=dtp)
arr51

array([(0., 0.,  50,  50,  50), (5., 5., 100, 100, 100)],
      dtype=[('x', '<f8'), ('y', '<f8'), ('r', 'u1'), ('g', 'u1'), ('b', 'u1')])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [51]:
coor = np.random.normal(loc=50, scale=50, size=(100, 2))
# print(coor)

dists = np.array([((coor - point) ** 2).sum(axis=1) for point in coor])
dists.shape
dists[0]

array([    0.        ,  3385.27345642,  9032.35784457, 13608.66074971,
       43349.4987171 , 16876.40356131, 13920.85228908,  3483.98142505,
       34300.8925819 , 24954.318049  , 12417.45481255, 29075.88212397,
       23502.53509809,  7703.97915307,  6564.13332823,  8989.62172023,
       18758.97972688, 19695.65067046,  7654.40661501, 57178.67386337,
       12691.70354429, 22938.67785326, 19860.2548006 , 35770.09703283,
       24579.42822288, 15291.07696723, 18843.6416711 , 10094.48692809,
       35033.24723046, 19705.59403932, 19628.84228908,  2205.89333442,
       19434.16204384, 18790.21553826, 18678.16966766,  5472.2292718 ,
        1863.44939942,  5353.09508051,  9101.76631876, 31069.73757704,
       18693.02227606, 22811.27075277, 19902.11187211, 42965.81440408,
       18823.56505371, 12041.56525627, 11326.57060204, 25591.746473  ,
       19566.597151  , 60619.24337942, 19361.17454038, 37076.40439806,
       28107.24595313, 18251.99267281,  6202.12375002,  7214.13657296,
      

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [98]:
fl = np.float32(5.6)
fl = fl.astype(np.int32, copy=False)
fl

np.int32(5)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [53]:
np.genfromtxt('test18.txt', delimiter=',', dtype=float)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [103]:
arr55 = np.random.randn(10)
list(enumerate(arr55))
list(np.ndenumerate(arr55))

[((0,), np.float64(0.8776932433029885)),
 ((1,), np.float64(-0.16491261527181356)),
 ((2,), np.float64(1.2087454608471184)),
 ((3,), np.float64(-1.6502996978108633)),
 ((4,), np.float64(1.6360232019856957)),
 ((5,), np.float64(0.47169498142714067)),
 ((6,), np.float64(-1.8346701065760682)),
 ((7,), np.float64(-0.17325400901789897)),
 ((8,), np.float64(1.5172253775889502)),
 ((9,), np.float64(-0.7188128238792465))]

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [54]:
np.random.standard_normal((3, 3))

array([[ 1.35433049,  0.19762082,  2.52606557],
       [-0.58042352,  0.74440478,  0.84387662],
       [ 0.3312261 ,  1.02335051,  0.8206595 ]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [104]:
p = 5

mat57 = np.zeros((5, 5))
x = np.random.choice(5, 5, False)
y = np.random.choice(5, 5, False)

vals = np.random.randint(1, 10, p)

mat57[x, y] = vals
mat57

array([[0., 4., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 7.],
       [0., 0., 0., 7., 0.],
       [9., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [56]:
mat58 = np.arange(1, 13).reshape(4, 3)
print(mat58)

mat58 - mat58.mean(axis=1, keepdims=True)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 59. How to sort an array by the nth column? (★★☆)

In [57]:
mat59 = np.array([
    [2, 1, 3],
    [3, 2, 4],
    [1, 3, 5],
])

inxs = np.argsort(mat59[:, 0])
mat59[inxs]

array([[1, 3, 5],
       [2, 1, 3],
       [3, 2, 4]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [58]:
mat60 = np.arange(25).reshape(5, 5)
mat60[:, [3, 1]] = 0
print(mat60)

mat60.sum(axis=0) == 0

[[ 0  0  2  0  4]
 [ 5  0  7  0  9]
 [10  0 12  0 14]
 [15  0 17  0 19]
 [20  0 22  0 24]]


array([False,  True, False,  True, False])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [59]:
arr61 = np.arange(3, 50, 5)
print(arr61)

val = 9
arr61[np.abs(arr61 - val).argmin()]

[ 3  8 13 18 23 28 33 38 43 48]


np.int64(8)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(1, 4)
B = A.reshape(-1, 1)

# res = np.empty((3, 3))
# for i in range(3):
#     for j in range(3):
#         res[i, j] = A[i] + B[j, 0]

# res

# A + B

array([[2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

#### 63. Create an array class that has a name attribute (★★☆)

In [61]:
class NameArray:
    def __init__(self, name: str, data: np.ndarray):
        self.name = name
        self.data = data

    def __str__(self):
        return f'Array {self.name}\n{self.data}'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [110]:
inxs = [0, 1, 1, 5]
arr64 = np.arange(10)
print(arr64)
arr64[inxs] += 1
arr64

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 2, 3, 4, 6, 6, 7, 8, 9])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [63]:
X = np.array([2, 3, 4, 5])
I = np.array([0, 2, 1, 0])
F = np.zeros(3)

np.add.at(F, I, X)
F

array([7., 4., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [111]:
img = np.array([
    [[123, 34, 45], [12, 255, 0], [0, 0, 0]],
    [[123, 34, 45], [255, 255, 255], [12, 255, 0]],
    [[0, 128, 255], [255, 0, 0], [0, 0, 0]]
])

np.unique(img.reshape(-1, 3), axis=0)

array([[  0,   0,   0],
       [  0, 128, 255],
       [ 12, 255,   0],
       [123,  34,  45],
       [255,   0,   0],
       [255, 255, 255]])

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [64]:
arr67 = np.random.randn(5, 5, 5, 5)
arr67.sum(axis=(2, 3))

array([[ -7.42028996,   3.69596681,  -0.30302388,   6.23550117,
        -10.44431407],
       [  6.42141785,   3.58678312,  -0.62564355,  -3.28463803,
        -17.16325992],
       [ -2.9899309 ,   0.22857621,  -2.86361013,   0.50630895,
         -4.72249086],
       [ -2.65423359,   0.3400049 ,   1.54599966,   0.9200183 ,
          1.30242701],
       [ -1.44627068,   1.76414196,   4.30448398,  -0.95882114,
          4.0353446 ]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [114]:
D = np.arange(1, 10)
S = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])

print(D)
print(S)

sums = np.bincount(S, weights=D)
counts = np.bincount(S)
sums / counts

[1 2 3 4 5 6 7 8 9]
[0 0 0 1 1 1 2 2 2]


array([2., 5., 8.])

#### 69. How to get the diagonal of a dot product? (★★★)

In [66]:
a = np.arange(10, 14).reshape(2, 2)
b = np.arange(20, 24).reshape(2, 2)

res = a @ b
print(res)
np.diag(res)

[[442 463]
 [526 551]]


array([442, 551])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [67]:
arr70 = np.array([1, 2, 3, 4, 5])

res = np.zeros(len(arr70) + (len(arr70) -1) * 3)
res[::4] = arr70
res

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [117]:
a = np.random.randn(5, 5, 3)
b = np.random.randn(5, 5)

a * b[:, :, np.newaxis]

array([[[ 8.61658776e-02, -1.61175785e-01, -9.68567373e-02],
        [ 3.53392424e-02, -1.68153878e-01, -2.85139474e-01],
        [ 1.26709807e+00,  1.18788168e+00,  8.36845129e-01],
        [ 2.09966663e+00,  4.01185665e-01, -9.39072020e-01],
        [-3.82766894e-01, -9.28586336e-04,  1.52696057e-01]],

       [[ 4.13923313e-01, -2.00820895e-01,  1.64752219e+00],
        [ 1.09352903e+00,  3.66503550e-01, -7.90698864e-01],
        [ 3.18153393e-01,  1.45828385e-01, -1.39720046e-01],
        [ 1.65901221e-01, -2.13677413e-02, -3.54336531e-02],
        [-4.95174090e-01, -1.11651185e+00,  1.40884748e+00]],

       [[-1.69646064e-01, -3.04086302e-02, -1.35532352e+00],
        [-1.36517338e-01,  2.61046298e-02,  3.88319709e-01],
        [-1.48323568e-01, -1.97800496e-01,  3.10142865e-02],
        [-7.39605801e-02, -8.02907333e-02,  1.26298226e-02],
        [ 2.13554035e-03,  1.12851619e-03, -1.72935615e-03]],

       [[ 7.01390767e-01,  4.87849480e-01, -5.27667309e-01],
        [-2.221484

#### 72. How to swap two rows of an array? (★★★)

In [69]:
arr72 = np.arange(9).reshape(3, 3)
print(arr72)

arr72[[0, -1]] = arr72[[-1, 0]]
arr72

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [70]:
arr73 = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [1, 3, 4],
    [3, 4, 5],
    [2, 4, 5],
    [1, 4, 5],
    [4, 5, 6],
    [3, 5, 6],
    [2, 5, 6],
    [1, 5, 6]
])

ab = np.hstack([arr73[:, [0]], arr73[:, [1]]])
bc = np.hstack([arr73[:, [1]], arr73[:, [2]]])
ac = np.hstack([arr73[:, [0]], arr73[:, [2]]])

unique_lines = np.vstack([ab, bc, ac])
unique_lines = np.sort(unique_lines, axis=1)
np.unique(unique_lines, axis=0)

array([[1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [1, 6],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [3, 4],
       [3, 5],
       [3, 6],
       [4, 5],
       [4, 6],
       [5, 6]])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [118]:
C = np.array([0, 2, 1, 3])
np.repeat(np.arange(len(C)), C)

array([1, 1, 2, 3, 3, 3])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [119]:
arr75 = np.array([1, 2, 3, 4, 5])
size = 3

cumsum = np.cumsum(arr75)
print(cumsum)

cumsum[size:] = cumsum[size:] - cumsum[:-size]
print(cumsum)

cumsum[size - 1:] / size

[ 1  3  6 10 15]
[ 1  3  6  9 12]


array([2., 3., 4.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [73]:
Z = np.array([1, 2, 3])

res = np.empty((len(Z) + 1, len(Z)))
for i in range(len(Z) + 1):
    res[i] = Z
    Z = np.roll(Z, 1)

res

array([[1., 2., 3.],
       [3., 1., 2.],
       [2., 3., 1.],
       [1., 2., 3.]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [74]:
arr77 = np.array([True])
arr77[:] = ~arr77
arr77

array([False])

In [75]:
fl = np.array([2.3])
fl *= -1
fl

array([-2.3])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [76]:
P0 = np.array([[0, 0], [5, 5]])
P1 = np.array([[1, 2], [6, 6]])
p = np.array([2, 2])

v = P1 - P0
w = p - P0

t = (w * v) / (v ** 2).sum(axis=1)

closest = P0 + t * v
dist = np.linalg.norm(p - closest, ord=2, axis=1)
dist

array([2.56124969, 2.83019434])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [77]:
P0 = np.array([[0, 0], [5, 5]])
P1 = np.array([[1, 2], [6, 6]])
P = np.array([[2, 2], [3, 3], [0, 1]])

res = np.empty((len(P), len(P0)))
for i in range(len(P)):
    v = P1 - P0
    w = P[i] - P0

    t = (w * v) / (v ** 2).sum(axis=1)

    closest = P0 + t * v
    res[i] = np.linalg.norm(P[i] - closest, ord=2, axis=1)

res

array([[2.56124969, 2.83019434],
       [3.84187454, 1.88679623],
       [1.        , 4.47213595]])

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [78]:
def extract_subarray(arr, center, shape, fill=0):
    pass

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [79]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
s = 4
res = np.empty((len(Z) - s + 1, s), dtype=int)

for i in range(len(Z) -s + 1):
    res[i] = Z[i:i + s]

res

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [80]:
mat = np.array([
    [0, 2],
    [0, 1]
])

np.linalg.matrix_rank(mat)

np.int64(1)

#### 83. How to find the most frequent value in an array?

In [81]:
arr83 = np.array([1, 2, 3, 3, 4, 5])
uni, counts = np.unique(arr83, return_counts=True)
uni[counts.argmax()]

np.int64(3)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [82]:
mat = np.random.randint(1, 100, (10, 10))
print(mat)

for i in range(0, mat.shape[0] - 3 + 1):
    for j in range(0, mat.shape[1] - 3 + 1):
        block = mat[i:i+3, j:j+3]
        print(block)

[[35 19 86 62 32 30 18 27 41  4]
 [11 57 62 49 58 94 77 20 91 83]
 [95 56 15 50 36 94 82 54 36 70]
 [16 43 37 10 81 35 53 22 61  1]
 [51 51 37 16 79 70 83 23 96 53]
 [80 38 46 89 24 87 79 21 15 38]
 [39 23 86 65  8 37 76 51 96 56]
 [99 67 37 25 22 79 77 52 32 59]
 [92 61 56 92  2 29 69 28 86 47]
 [68  6 10  4  9 84  4 55 20 32]]
[[35 19 86]
 [11 57 62]
 [95 56 15]]
[[19 86 62]
 [57 62 49]
 [56 15 50]]
[[86 62 32]
 [62 49 58]
 [15 50 36]]
[[62 32 30]
 [49 58 94]
 [50 36 94]]
[[32 30 18]
 [58 94 77]
 [36 94 82]]
[[30 18 27]
 [94 77 20]
 [94 82 54]]
[[18 27 41]
 [77 20 91]
 [82 54 36]]
[[27 41  4]
 [20 91 83]
 [54 36 70]]
[[11 57 62]
 [95 56 15]
 [16 43 37]]
[[57 62 49]
 [56 15 50]
 [43 37 10]]
[[62 49 58]
 [15 50 36]
 [37 10 81]]
[[49 58 94]
 [50 36 94]
 [10 81 35]]
[[58 94 77]
 [36 94 82]
 [81 35 53]]
[[94 77 20]
 [94 82 54]
 [35 53 22]]
[[77 20 91]
 [82 54 36]
 [53 22 61]]
[[20 91 83]
 [54 36 70]
 [22 61  1]]
[[95 56 15]
 [16 43 37]
 [51 51 37]]
[[56 15 50]
 [43 37 10]
 [51 37 16]]
[[1

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [83]:
class Mat:
    def __init__(self, data):
        if not isinstance(data, np.ndarray):
            data = np.asarray(data)

        self.data = data

    def __setitem__(self, key, val):
        self.data[key] = val
        
        if isinstance(key, tuple):
            self.data[key[1], key[0]] = val

    def __str__(self):
        return str(self.data)


m = Mat(np.zeros((5, 5)))
print(m)

m[2, 3] = 1
print(m)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p = np.arange(27).reshape(3, 3, 3)
v = np.arange(3).reshape(-1, 1)

(p @ v).sum(axis=0) 

array([[ 96],
       [123],
       [150]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [85]:
arr = np.arange(16 * 16).reshape(16, 16)

b = np.array_split(arr, 4, axis=(0))
b = np.array_split(b, 4, axis=(1))
np.hstack([i.sum(axis=2) for i in b])

array([[ 120,  376,  632,  888],
       [1144, 1400, 1656, 1912],
       [2168, 2424, 2680, 2936],
       [3192, 3448, 3704, 3960]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [86]:
n = 2
arr = np.array([2, 3, 4, 5, 5,6 , 7,8 ,6])

arr[arr.argpartition(kth=n)[-n:]]

array([7, 8])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [121]:
A = [1, 2]
B = [3, 4]
C = [5, 6]

g = np.meshgrid(A, B, C, indexing='ij')
np.stack(g, axis=-1).reshape(-1, 3)

array([[1, 3, 5],
       [1, 3, 6],
       [1, 4, 5],
       [1, 4, 6],
       [2, 3, 5],
       [2, 3, 6],
       [2, 4, 5],
       [2, 4, 6]])

#### 91. How to create a record array from a regular array? (★★★)

In [88]:
arr = np.random.standard_normal((4, 3))

np.rec.fromarrays(arr, names=['a', 'b', 'c', 'd'])

rec.array([(0.38804296, 0.96619229,  0.10210735,  0.42813208),
           (0.73518036, 0.58810231,  0.32172879, -0.41466489),
           (1.08120722, 0.07535409, -0.89863188, -0.20871276)],
          dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8'), ('d', '<f8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [89]:
Z = np.arange(50)
Z ** 3 
np.pow(Z, 3)
Z * Z * Z

array([     0,      1,      8,     27,     64,    125,    216,    343,
          512,    729,   1000,   1331,   1728,   2197,   2744,   3375,
         4096,   4913,   5832,   6859,   8000,   9261,  10648,  12167,
        13824,  15625,  17576,  19683,  21952,  24389,  27000,  29791,
        32768,  35937,  39304,  42875,  46656,  50653,  54872,  59319,
        64000,  68921,  74088,  79507,  85184,  91125,  97336, 103823,
       110592, 117649])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [123]:
A = np.array([
    [1, 2, 3],
    [3, 2, 1],
    [4, 5, 6],
    [7, 8, 9],
    [2, 3, 4],
    [5, 1, 2],
    [6, 7, 8],
    [1, 4, 5]
])

B = np.array([
    [1, 2],
    [4, 5]
])

A[np.isin(A, B).sum(axis=1) >= 2]

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6],
       [2, 3, 4],
       [5, 1, 2],
       [1, 4, 5]])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [91]:
arr94 = np.array([
    [1, 1, 1],
    [2, 2, 3],
    [4, 4, 4],
    [5, 6, 5],
    [7, 7, 7],
    [8, 9, 10],
    [3, 3, 3],
    [6, 6, 7],
    [0, 0, 0],
    [2, 3, 2]
])


arr94[arr94.sum(axis=1) / 3 != arr94[:, 0]]

array([[ 2,  2,  3],
       [ 5,  6,  5],
       [ 8,  9, 10],
       [ 6,  6,  7],
       [ 2,  3,  2]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [92]:
arr95 = np.array([0, 1, 0, 2, 3])
arr95.astype(bool)

array([False,  True, False,  True,  True])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [93]:
arr96 = np.array([[2], [2], [3], [3], [4]])
np.unique(arr96, axis=0)

array([[2],
       [3],
       [4]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [124]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(np.einsum('i,i->', A, B)) # inner
print(np.einsum('i,j->ij', A, B)) # outer
print(np.einsum('i,i->', A, B)) # sum
print(np.einsum('i,i->i', A, B)) # mul

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
32
[ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [126]:
X = np.array([[2, 1, 3],
              [0.5, 1.5, 3],
              [1, 2, 2],
              [2.5, 2.5, 1]])

n = 6

((np.floor(X) == X).sum(axis=1) == 3) & (X.sum(axis=1) == n)

array([ True, False, False, False])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [97]:
X = np.array([1, 2, 3, 4, 5])
N = 100  

boot_means = np.empty(N)
for i in range(N):
    sample = np.random.choice(X, size=len(X), replace=True)
    boot_means[i] = np.mean(sample)

lower = np.percentile(boot_means, 2.5)
upper = np.percentile(boot_means, 97.5)
lower, upper 

(np.float64(1.895), np.float64(4.209999999999996))